# Generated by Django 4.2.4 on 2023-09-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minttrack_app', '0002_budget_month_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='goal',
            name='saved',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
