# Generated by Django 4.2.4 on 2023-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minttrack_app', '0005_goal_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='saved',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
