# Generated by Django 4.2.4 on 2023-09-06 08:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minttrack_app', '0003_alter_transaction_options_alter_goal_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='target_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 9, 6))]),
        ),
    ]
