# Generated by Django 4.2.4 on 2023-09-06 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minttrack_app', '0006_alter_goal_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='saved',
        ),
        migrations.CreateModel(
            name='GoalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_transactions', to='minttrack_app.goal')),
            ],
        ),
    ]
